// Server-backed TTS service. Audio is generated by the `tts` Supabase
// edge function (Kokoro server, OpenAI-compatible) and returned as a tiny
// MP3 we play through a single shared AudioContext. iOS Safari friendly:
// no model download, no WASM, no web worker.

import { supabase } from '@/integrations/supabase/client';

export type TtsModelState = 'idle' | 'loading' | 'ready' | 'error';

type Listener = (s: TtsState) => void;

export interface TtsState {
  modelState: TtsModelState;
  generatingId: string | null;
  playingId: string | null;
  error: string | null;
  progress: number;
}

const state: TtsState = {
  // No model to load — server-side TTS is always ready as soon as the user
  // is signed in. Existing UI watches this for the green "Voice ready" dot.
  modelState: 'ready',
  generatingId: null,
  playingId: null,
  error: null,
  progress: 100,
};

const listeners = new Set<Listener>();
function emit() { for (const l of listeners) l({ ...state }); }

// Single shared AudioContext (must be created/resumed inside a user gesture
// on iOS). One in-flight source at a time.
let audioCtx: AudioContext | null = null;
let currentSource: AudioBufferSourceNode | null = null;
let currentAbort: AbortController | null = null;

function getAudioContext(): AudioContext | null {
  if (typeof window === 'undefined') return null;
  if (audioCtx) return audioCtx;
  const Ctor: typeof AudioContext | undefined =
    (window as any).AudioContext || (window as any).webkitAudioContext;
  if (!Ctor) return null;
  // iOS Safari: route through "playback" session so audio plays even with
  // the silent switch on.
  try {
    const session = (navigator as any).audioSession;
    if (session && session.type !== 'playback') session.type = 'playback';
  } catch { /* ignore */ }
  audioCtx = new Ctor();
  return audioCtx;
}

async function unlockAudio() {
  const ctx = getAudioContext();
  if (!ctx) return;
  try {
    if (ctx.state === 'suspended') await ctx.resume();
    // Play one tiny silent buffer to fully unlock playback on iOS.
    try {
      const buf = ctx.createBuffer(1, 1, 22050);
      const src = ctx.createBufferSource();
      src.buffer = buf;
      src.connect(ctx.destination);
      src.start(0);
    } catch { /* ignore */ }
  } catch (e) {
    console.warn('[tts] audioCtx.resume failed', e);
  }
}

function stopPlaybackOnly() {
  if (currentSource) {
    try { currentSource.stop(); } catch { /* ignore */ }
    try { currentSource.disconnect(); } catch { /* ignore */ }
    currentSource.onended = null;
    currentSource = null;
  }
  if (currentAbort) {
    try { currentAbort.abort(); } catch { /* ignore */ }
    currentAbort = null;
  }
}

function stripForSpeech(text: string) {
  return String(text || '')
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/!\[[^\]]*\]\([^)]+\)/g, ' ')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .replace(/[*_`>#~|]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 4000);
}

function base64ToBytes(b64: string): Uint8Array {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

async function fetchSpeech(text: string, voice: string, signal: AbortSignal): Promise<Blob> {
  // Raw fetch (not supabase.functions.invoke) so the binary base64 payload
  // is returned verbatim without any client-side JSON mangling.
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
  const ANON = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string;
  const { data: { session } } = await supabase.auth.getSession();
  const token = session?.access_token || ANON;
  const res = await fetch(`${SUPABASE_URL}/functions/v1/tts`, {
    method: 'POST',
    signal,
    headers: {
      'Content-Type': 'application/json',
      apikey: ANON,
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify({ text, voice }),
  });
  if (!res.ok) {
    let detail = '';
    try { detail = JSON.stringify(await res.json()); } catch { /* ignore */ }
    throw new Error(`TTS failed (${res.status}): ${detail || res.statusText}`);
  }
  const json = await res.json();
  if (!json?.audio) throw new Error('TTS response missing audio');
  const bytes = base64ToBytes(json.audio);
  return new Blob([bytes.buffer as ArrayBuffer], { type: json.mimeType || 'audio/mpeg' });
}

export const ttsService = {
  subscribe(l: Listener) {
    listeners.add(l);
    l({ ...state });
    return () => { listeners.delete(l); };
  },
  getState(): TtsState { return { ...state }; },
  // No-op kept for backwards compatibility with existing call sites.
  preload(_voice?: string) { /* server-side TTS — nothing to preload */ },
  warm(_voice: string) { /* no-op */ },

  async speak(text: string, voice: string, id: string) {
    // CRITICAL: kick AudioContext unlock synchronously inside the user gesture.
    void unlockAudio();

    const clean = stripForSpeech(text);
    if (!clean) return;

    stopPlaybackOnly();
    const abort = new AbortController();
    currentAbort = abort;
    state.generatingId = id;
    state.playingId = null;
    state.error = null;
    emit();

    try {
      const blob = await fetchSpeech(clean, voice, abort.signal);
      console.log('TTS blob bytes:', blob.size);
      if (abort.signal.aborted) return;

      const ctx = getAudioContext();
      if (!ctx) throw new Error('Web Audio not supported on this device.');
      if (ctx.state === 'suspended') {
        try { await ctx.resume(); } catch { /* ignore */ }
      }

      const arrayBuf = await blob.arrayBuffer();
      const audioData: AudioBuffer = await new Promise((resolve, reject) => {
        try {
          const p = ctx.decodeAudioData(arrayBuf.slice(0), resolve, reject);
          if (p && typeof (p as any).then === 'function') {
            (p as Promise<AudioBuffer>).then(resolve, reject);
          }
        } catch (e) { reject(e); }
      });

      if (abort.signal.aborted) return;

      const source = ctx.createBufferSource();
      source.buffer = audioData;
      source.connect(ctx.destination);
      source.onended = () => {
        if (currentSource === source) currentSource = null;
        if (state.playingId === id) {
          state.playingId = null;
          emit();
        }
      };
      currentSource = source;
      state.generatingId = null;
      state.playingId = id;
      emit();
      source.start(0);
    } catch (err: any) {
      if (abort.signal.aborted) return;
      console.error('[tts] speak failed', err);
      state.error = String(err?.message ?? err);
      state.generatingId = null;
      state.playingId = null;
      emit();
    }
  },

  stop() {
    stopPlaybackOnly();
    if (state.generatingId || state.playingId) {
      state.generatingId = null;
      state.playingId = null;
      emit();
    }
  },
};
